eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management.security.enabled: false

server:
  port: 8088
spring:
  application:
    name: spring-boot-admin